using Farbod.Prefabbricato.Backend;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace Farbod.Prefabbricato
{
    /// <summary>
    /// <!--  
    /// AI WARNING.
    /// This script was originally generated by Claude Haiku 4.5
    /// I only iterated upon it. it is not written by me unlike the other scripts.
    /// And so the coding patterns will differ from the rest of the project.
    /// -->
    /// 
    /// <para>
    /// A VisualElement wrapping a UI Toolkit TreeView that displays the folder
    /// hierarchy found under a single project-relative root directory
    /// (e.g. "Assets" or "Assets/Art/Textures").
    /// </para>
    ///
    /// <para>
    /// NOTE ON UNITY VERSIONS:
    /// This relies on TreeView mutation APIs (AddItem / TryRemoveItem) that were
    /// introduced around Unity 2022.2. On older editors you'll need to rebuild the
    /// whole tree instead of inserting a single placeholder item for folder creation.
    /// </para>
    /// </summary>
    public class LibraryProjectView : VisualElement
    {
        /// <summary>
        /// Raised when a folder item in the tree is double-clicked.
        /// The argument is the folder's path relative to the project root
        /// (e.g. "Assets/Art/Textures"), using forward slashes.
        /// </summary>
        public event Action<string> onFolderDoubleClicked;

        private readonly UnityEngine.UIElements.TreeView _treeView;
        private readonly bool _allowFileActions;
        private readonly HashSet<int> _handledPendingIds = new();

        private int _nextId;
        private int _nextPendingId;
        private string _rootRelativePath;

        // Pulled via EditorGUIUtility so they respect the current editor skin.
        private static Texture2D FolderClosedIcon =>
            EditorGUIUtility.IconContent("Folder Icon").image as Texture2D;

        private static Texture2D FolderOpenIcon =>
            EditorGUIUtility.IconContent("FolderOpened Icon").image as Texture2D;

        // Unity's Project window uses distinct icons for empty folders. If a given
        // Editor version doesn't ship them under these names, fall back to the
        // regular folder icons rather than showing nothing.
        private static Texture2D FolderClosedEmptyIcon =>
            EditorGUIUtility.IconContent("FolderEmpty Icon").image as Texture2D ?? FolderClosedIcon;

        private static Texture2D FolderOpenEmptyIcon =>
            EditorGUIUtility.IconContent("FolderOpenEmpty Icon").image as Texture2D ?? FolderOpenIcon;

        /// <param name="rootRelativePath">Project-relative root folder to display, e.g. "Assets".</param>
        /// <param name="allowFileActions">
        /// If true, adds Rename / Create Folder / Delete to the context menu, backed by
        /// Unity's AssetDatabase. This requires <paramref name="rootRelativePath"/> (and
        /// therefore every folder under it) to live under "Assets" or "Packages".
        /// </param>
        public LibraryProjectView(string rootRelativePath, bool allowFileActions)
        {
            _allowFileActions = allowFileActions;
            style.flexGrow = 1;

            _treeView = new UnityEngine.UIElements.TreeView
            {
                fixedItemHeight = 20,
                style = { flexGrow = 1 },
                makeItem = MakeItem,
                bindItem = BindItem,
                unbindItem = UnbindItem
            };
            _treeView.style.backgroundColor = StyleKeyword.Initial;

            _treeView.AddManipulator(new ContextualMenuManipulator(PopulateBackgroundContextMenu));
            _treeView.RegisterCallback<KeyDownEvent>(OnTreeViewKeyDown);

            Add(_treeView);

            SetRoot(rootRelativePath);
        }

        /// <summary>
        /// Rebuilds the tree using the given project-relative root path
        /// (e.g. "Assets" or "Assets/MyFolder").
        /// </summary>
        public void SetRoot(string rootRelativePath)
        {
            _rootRelativePath = rootRelativePath;
            _nextId = 0;

            WarnIfRootIncompatibleWithFileActions(rootRelativePath);

            var items = BuildTree(rootRelativePath);
            _treeView.SetRootItems(items);
            _treeView.Rebuild();
        }
        /// <summary>Forces a full rescan of the current root and rebuilds the tree,
        /// preserving which folders were expanded beforehand.</summary>
        public void Refresh(string newPath = null)
        {
            string path = !string.IsNullOrEmpty(newPath) ? newPath : _rootRelativePath;
            if (string.IsNullOrEmpty(path)) return;

            var expandedPaths = CaptureExpandedPaths();
            SetRoot(path);
            RestoreExpandedPaths(expandedPaths);
        }

        /// <summary>
        /// Collects the relative paths of every currently expanded folder. Paths
        /// are used instead of ids since ids are reassigned from scratch on every
        /// rebuild (see BuildTree/BuildItemRecursive), so ids alone can't be used
        /// to restore state after a Refresh.
        /// </summary>
        private HashSet<string> CaptureExpandedPaths()
        {
            var result = new HashSet<string>();
            var controller = _treeView.viewController;

            foreach (int id in controller.GetAllItemIds())
            {
                if (!controller.IsExpanded(id)) continue;

                var data = _treeView.GetItemDataForId<FolderEntry>(id);
                if (!data.IsPendingCreate && !string.IsNullOrEmpty(data.RelativePath))
                    result.Add(data.RelativePath);
            }

            return result;
        }

        /// <summary>Re-expands every folder in the freshly rebuilt tree whose relative path was previously expanded.</summary>
        private void RestoreExpandedPaths(HashSet<string> expandedPaths)
        {
            if (expandedPaths.Count == 0) return;

            var controller = _treeView.viewController;
            foreach (int id in controller.GetAllItemIds())
            {
                var data = _treeView.GetItemDataForId<FolderEntry>(id);
                if (!data.IsPendingCreate && expandedPaths.Contains(data.RelativePath))
                    _treeView.ExpandItem(id);
            }
        }

        // ---------------------------------------------------------------
        // Tree construction
        // ---------------------------------------------------------------

        private List<TreeViewItemData<FolderEntry>> BuildTree(string rootRelativePath)
        {
            var result = new List<TreeViewItemData<FolderEntry>>();

            string absoluteRoot = ToAbsolutePath(rootRelativePath);
            if (!Directory.Exists(absoluteRoot))
            {
                Debug.LogWarning($"[ProjectTreeView] Root folder does not exist: {absoluteRoot}");
                return result;
            }

            foreach (var folderPath in ScanFolders(absoluteRoot))
            {
                result.Add(BuildItemRecursive(folderPath));
            }

            return result;
        }

        /// <summary>
        /// Returns the immediate subfolders of the given absolute directory path.
        /// This is intentionally isolated so it can be overridden or edited later
        /// (e.g. to add filtering, ignore hidden/meta folders, sort differently, etc.)
        /// without touching the rest of the tree-building logic.
        /// </summary>
        protected virtual IEnumerable<string> ScanFolders(string absoluteDirectoryPath)
        {
            return Directory.GetDirectories(absoluteDirectoryPath)
                .Where(p => !IsHiddenFolder(p))
                .OrderBy(p => Path.GetFileName(p), StringComparer.OrdinalIgnoreCase);
        }


        /// <summary>
        /// Returns true for folders that should be skipped entirely, such as
        /// ".git", ".vs", or any folder with the OS "hidden" attribute set.
        /// </summary>
        protected virtual bool IsHiddenFolder(string absoluteFolderPath)
        {
            string name = Path.GetFileName(absoluteFolderPath);
            if (name.StartsWith(".", StringComparison.Ordinal))
                return true;

            try
            {
                return (File.GetAttributes(absoluteFolderPath) & FileAttributes.Hidden) != 0;
            }
            catch (IOException)
            {
                return false;
            }
        }

        private TreeViewItemData<FolderEntry> BuildItemRecursive(string absoluteFolderPath)
        {
            int id = _nextId++;
            string relativePath = ToRelativePath(absoluteFolderPath);
            string name = Path.GetFileName(absoluteFolderPath);

            var children = new List<TreeViewItemData<FolderEntry>>();
            foreach (var childPath in ScanFolders(absoluteFolderPath))
            {
                children.Add(BuildItemRecursive(childPath));
            }

            var data = FolderEntry.Existing(name, relativePath, IsFolderEmpty(relativePath));
            return new TreeViewItemData<FolderEntry>(id, data, children);
        }

        /// <summary>
        /// Determines whether a folder should be marked "empty" in the tree.
        /// Placeholder implementation — for now this only checks whether any
        /// prefab assets exist anywhere under the folder. Replace or extend this
        /// later (e.g. check for any asset at all) without touching the rest of
        /// the tree-building or icon logic.
        /// </summary>
        protected virtual bool IsFolderEmpty(string relativePath)
        {
            //Check for subfolders
            string[] folders = AssetDatabase.GetSubFolders(relativePath);
            if (folders.Length != 0)
                return false;

            //Check for assets
            string[] guids = AssetDatabase.FindAssets("t:Prefab", new[] { relativePath });
            return guids.Length == 0;
        }

        // ---------------------------------------------------------------
        // TreeView item visuals
        // ---------------------------------------------------------------

        private VisualElement MakeItem()
        {
            var row = new VisualElement
            {
                name = "folder-row",
                style =
                {
                    flexDirection = FlexDirection.Row,
                    alignItems = Align.Center
                }
            };

            var icon = new Image
            {
                name = "folder-icon",
                scaleMode = ScaleMode.ScaleToFit,
                style =
                {
                    width = 16,
                    height = 16,
                    marginRight = 4,
                    flexShrink = 0
                }
            };

            var label = new Label { name = "folder-label" };

            row.Add(icon);
            row.Add(label);

            row.RegisterCallback<MouseDownEvent>(OnRowMouseDown);
            row.AddManipulator(new ContextualMenuManipulator(evt => PopulateContextMenu(evt, row)));

            return row;
        }

        private void BindItem(VisualElement element, int index)
        {
            var data = _treeView.GetItemDataForIndex<FolderEntry>(index);
            int id = _treeView.GetIdForIndex(index);

            var label = element.Q<Label>("folder-label");
            var icon = element.Q<Image>("folder-icon");

            // A pooled row might still carry a leftover rename/create field from
            // whatever item it was previously bound to.
            element.Q<TextField>("folder-name-field")?.RemoveFromHierarchy();
            label.style.display = DisplayStyle.Flex;

            // The built-in expand/collapse arrow lives outside the VisualElement
            // returned by makeItem, so bindItem alone won't re-fire when this
            // item's own expanded state toggles. A light periodic check keeps
            // the icon in sync without depending on a specific expand/collapse
            // event API that may not exist across all Editor versions.
            var scheduled = element.schedule.Execute(() => UpdateIcon(element, id, data.IsEmpty)).Every(500);
            element.userData = new RowState(data, id, scheduled);

            if (data.IsPendingCreate)
            {
                icon.image = FolderClosedIcon;
                label.style.display = DisplayStyle.None;
                CreatePendingField(element, label, id, data.ParentRelativePath);
                return;
            }

            label.text = data.Name;
            UpdateIcon(element, id, data.IsEmpty);
        }

        private void UnbindItem(VisualElement element, int index)
        {
            if (element.userData is RowState state)
                state.ScheduledItem.Pause();

            element.userData = null;
        }

        private void UpdateIcon(VisualElement element, int id, bool isEmpty)
        {
            var icon = element.Q<Image>("folder-icon");
            if (icon == null) return;

            bool expanded = _treeView.IsExpanded(id);
            icon.image = isEmpty
                ? (expanded ? FolderOpenEmptyIcon : FolderClosedEmptyIcon)
                : (expanded ? FolderOpenIcon : FolderClosedIcon);
        }


        private void OnRowMouseDown(MouseDownEvent evt)
        {
            if (evt.clickCount != 2) return;

            var row = (VisualElement)evt.currentTarget;
            if (row.Q<TextField>() != null) return; // ignore while a rename/create field is active
            if (row.userData is not RowState state || state.Entry.IsPendingCreate) return;

            onFolderDoubleClicked?.Invoke(state.Entry.RelativePath);
            evt.StopPropagation();
        }

        /// <summary>
        /// Keyboard inputs for tree view
        /// </summary>
        /// <param name="evt"></param>
        private void OnTreeViewKeyDown(KeyDownEvent evt)
        {
            if (!_allowFileActions) return;

            int index = _treeView.selectedIndex;
            if (index < 0) return; // nothing selected

            var row = _treeView.GetRootElementForIndex(index)?.Q("folder-row");
            if (row == null) return; // selected item isn't currently realized/visible

            if (row.Q<TextField>() != null) return; // already renaming/creating on this row
            if (row.userData is not RowState state || state.Entry.IsPendingCreate) return;

            // Rename
            if (evt.keyCode == KeyCode.F2)
            {
                BeginRename(row);
                evt.StopPropagation();
            }
            // Delete
            else if (evt.keyCode == KeyCode.Delete)
            {
                DeleteFolder(row);
                evt.StopPropagation();
            }

        }


        // ---------------------------------------------------------------
        // Context menu
        // ---------------------------------------------------------------

        private void PopulateContextMenu(ContextualMenuPopulateEvent evt, VisualElement row)
        {
            if (row.userData is not RowState state || state.Entry.IsPendingCreate)
                return;

            var entry = state.Entry;

            if (_allowFileActions)
            {
                evt.menu.AppendAction("Create Folder", _ => BeginCreateFolder(row));
                evt.menu.AppendAction("Delete", _ => DeleteFolder(row));
                evt.menu.AppendAction("Rename", _ => BeginRename(row));
                evt.menu.AppendSeparator();
            }

            // Always available, regardless of allowFileActions.
            evt.menu.AppendAction("Show In Project", _ => PingInProjectWindow(entry.RelativePath));
            evt.menu.AppendAction("Show In Explorer", _ => PingInFileExplorer(entry.RelativePath));

            // Prevent this from bubbling up into the background menu below.
            evt.StopPropagation();
        }

        /// <summary>
        /// Populates the context menu shown when right-clicking empty space in the
        /// tree view (i.e. not on top of any folder row). Always available,
        /// regardless of allowFileActions.
        /// </summary>
        private void PopulateBackgroundContextMenu(ContextualMenuPopulateEvent evt)
        {
            if (_allowFileActions)
            {
                evt.menu.AppendAction("Create Folder", _ => BeginCreateFolderAt(-1, _rootRelativePath));
                evt.menu.AppendSeparator();
            }

            evt.menu.AppendAction("Show In Explorer", _ => PingInFileExplorer(_rootRelativePath));
            evt.menu.AppendAction("Show In Project", _ => PingInProjectWindow(_rootRelativePath));
            evt.menu.AppendAction("Change Library Path", _ => PrefabbricatoSettings.SelectLibraryDirectory());
        }

        private static void PingInProjectWindow(string relativePath)
        {
            var asset = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(relativePath);
            if (asset == null)
            {
                Debug.LogWarning($"[ProjectTreeView] Could not find an asset at '{relativePath}' to select in the Project window.");
                return;
            }

            Selection.activeObject = asset;
            EditorGUIUtility.PingObject(asset);
        }

        protected virtual void PingInFileExplorer(string relativePath)
        {
            PathUtilities.OpenInFileBrowser(PathUtilities.GetAbsolutePathFromProject(relativePath));
        }

        // ---------------------------------------------------------------
        // Rename (allowFileActions)
        // ---------------------------------------------------------------

        private void BeginRename(VisualElement row)
        {
            if (row.userData is not RowState state) return;

            var label = row.Q<Label>("folder-label");
            if (label == null || row.Q<TextField>("folder-name-field") != null)
                return; // already renaming

            var textField = new TextField { name = "folder-name-field", value = state.Entry.Name };
            textField.style.flexGrow = 1;
            row.Insert(row.IndexOf(label), textField);
            label.style.display = DisplayStyle.None;

            textField.RegisterCallback<KeyDownEvent>(e =>
            {
                if (e.keyCode == KeyCode.Return || e.keyCode == KeyCode.KeypadEnter)
                {
                    CommitRename(row, state.Entry, textField.value);
                    e.StopPropagation();
                }
                else if (e.keyCode == KeyCode.Escape)
                {
                    CancelRename(row);
                    e.StopPropagation();
                }
            });
            textField.RegisterCallback<FocusOutEvent>(_ => CommitRename(row, state.Entry, textField.value));

            textField.schedule.Execute(() =>
            {
                textField.Focus();
                textField.SelectAll();
            });
        }

        private void CommitRename(VisualElement row, FolderEntry entry, string newName)
        {
            var textField = row.Q<TextField>("folder-name-field");
            if (textField == null) return; // already committed or cancelled (Enter + FocusOut can both fire)

            newName = newName?.Trim();

            if (string.IsNullOrEmpty(newName) || newName == entry.Name)
            {
                CancelRename(row);
                return;
            }

            // Unity-managed rename: updates the .meta file and any asset references.
            string error = AssetDatabase.RenameAsset(entry.RelativePath, newName);
            if (!string.IsNullOrEmpty(error))
            {
                Debug.LogWarning($"[ProjectTreeView] Rename failed for '{entry.RelativePath}': {error}");
                CancelRename(row);
                return;
            }

            row.Remove(textField);
            var label = row.Q<Label>("folder-label");
            if (label != null) label.style.display = DisplayStyle.Flex;

            Refresh(); // this folder's path (and every child path below it) changed on disk
        }

        private void CancelRename(VisualElement row)
        {
            var textField = row.Q<TextField>("folder-name-field");
            if (textField == null) return;

            row.Remove(textField);
            var label = row.Q<Label>("folder-label");
            if (label != null) label.style.display = DisplayStyle.Flex;
        }

        // ---------------------------------------------------------------
        // Create folder (allowFileActions)
        // ---------------------------------------------------------------

        private void BeginCreateFolder(VisualElement row)
        {
            if (row.userData is not RowState state) return;

            BeginCreateFolderAt(state.Id, state.Entry.RelativePath);
        }

        /// <summary>
        /// Inserts a temporary, editable placeholder folder item under the given
        /// parent (-1 for a root-level folder) and begins creating it there.
        /// </summary>
        private void BeginCreateFolderAt(int parentId, string parentPath)
        {
            // Negative ids are reserved for not-yet-created placeholder items,
            // so they never collide with the real (>= 0) ids from BuildTree.
            int tempId = --_nextPendingId;

            var pendingEntry = FolderEntry.Pending(parentPath);
            var itemData = new TreeViewItemData<FolderEntry>(tempId, pendingEntry, new List<TreeViewItemData<FolderEntry>>());

            if (parentId >= 0)
                _treeView.ExpandItem(parentId);

            _treeView.AddItem(itemData, parentId); // rebuilds + binds, which schedules focus on the new field
        }


        private void CreatePendingField(VisualElement element, Label label, int tempId, string parentRelativePath)
        {
            var textField = new TextField { name = "folder-name-field", value = "New Folder" };
            textField.style.flexGrow = 1;
            element.Insert(element.IndexOf(label), textField);

            textField.RegisterCallback<KeyDownEvent>(e =>
            {
                if (e.keyCode == KeyCode.Return || e.keyCode == KeyCode.KeypadEnter)
                {
                    CommitCreateFolder(tempId, parentRelativePath, textField.value);
                    e.StopPropagation();
                }
                else if (e.keyCode == KeyCode.Escape)
                {
                    CancelCreateFolder(tempId);
                    e.StopPropagation();
                }
            });
            textField.RegisterCallback<FocusOutEvent>(_ => CommitCreateFolder(tempId, parentRelativePath, textField.value));

            textField.schedule.Execute(() =>
            {
                textField.Focus();
                textField.SelectAll();
            });
        }

        private void CommitCreateFolder(int tempId, string parentRelativePath, string folderName)
        {
            if (!_handledPendingIds.Add(tempId)) return; // Enter + FocusOut can both fire; only handle once

            folderName = folderName?.Trim();

            if (string.IsNullOrEmpty(folderName))
            {
                _treeView.TryRemoveItem(tempId);
                _treeView.RefreshItems();
                return;
            }

            string candidatePath = string.IsNullOrEmpty(parentRelativePath)
                ? folderName
                : $"{parentRelativePath}/{folderName}";

            if (AssetDatabase.IsValidFolder(candidatePath))
            {
                Debug.LogWarning($"[ProjectTreeView] A folder already exists at '{candidatePath}'.");
                _treeView.TryRemoveItem(tempId);
                _treeView.RefreshItems();
                return;
            }

            // Unity-managed folder creation: also generates the accompanying .meta file.
            string guid = AssetDatabase.CreateFolder(parentRelativePath, folderName);
            if (string.IsNullOrEmpty(guid))
                Debug.LogWarning($"[ProjectTreeView] Failed to create folder '{candidatePath}'.");

            _treeView.TryRemoveItem(tempId);
            Refresh(); // pick up the new folder as a proper, scanned entry
        }

        private void CancelCreateFolder(int tempId)
        {
            if (!_handledPendingIds.Add(tempId)) return;

            _treeView.TryRemoveItem(tempId);
            _treeView.RefreshItems();
        }

        // ---------------------------------------------------------------
        // Delete (allowFileActions)
        // ---------------------------------------------------------------

        private void DeleteFolder(VisualElement row)
        {
            if (row.userData is not RowState state) return;
            var entry = state.Entry;

            //Ask for confirmation if folder is not fully empty
            int assetsCount = AssetDatabase.FindAssets("", new[] { entry.RelativePath }).Length;
            if (assetsCount > 0)
            {
                bool confirmed = EditorUtility.DisplayDialog(
                "Delete Folder",
                $"Delete '{entry.Name}' and all {assetsCount} items inside?\nYou cannot undo this action.",
                "Delete",
                "Cancel");

                if (!confirmed) return;
            }


            // Unity-managed delete: respects .meta files and moves the asset to the OS trash where supported.
            if (!AssetDatabase.DeleteAsset(entry.RelativePath))
                Debug.LogWarning($"[ProjectTreeView] Failed to delete '{entry.RelativePath}'.");

            Refresh();
        }

        // ---------------------------------------------------------------
        // Path helpers
        // ---------------------------------------------------------------

        private static string ToAbsolutePath(string projectRelativePath)
        {
            string projectRoot = Directory.GetParent(Application.dataPath)!.FullName;
            return Path.GetFullPath(Path.Combine(projectRoot, projectRelativePath));
        }

        private static string ToRelativePath(string absolutePath)
        {
            string projectRoot = Directory.GetParent(Application.dataPath)!.FullName;
            string full = Path.GetFullPath(absolutePath);
            return full.Substring(projectRoot.Length + 1).Replace('\\', '/');
        }

        private static bool IsAssetDatabasePath(string relativePath) =>
            !string.IsNullOrEmpty(relativePath) &&
            relativePath.StartsWith("Assets", StringComparison.OrdinalIgnoreCase);

        private void WarnIfRootIncompatibleWithFileActions(string rootRelativePath)
        {
            if (_allowFileActions && !IsAssetDatabasePath(rootRelativePath))
            {
                Debug.LogWarning("[ProjectTreeView] allowFileActions is enabled, but the root path is not under " +
                                 "'Assets' or 'Packages'. Rename/Create Folder/Delete use Unity's AssetDatabase, " +
                                 "which only manages paths under those folders.");
            }
        }

        private readonly struct FolderEntry
        {
            public readonly string Name;
            public readonly string RelativePath;
            public readonly string ParentRelativePath;
            public readonly bool IsPendingCreate;
            public readonly bool IsEmpty;

            private FolderEntry(string name, string relativePath, string parentRelativePath, bool isPendingCreate, bool isEmpty)
            {
                Name = name;
                RelativePath = relativePath;
                ParentRelativePath = parentRelativePath;
                IsPendingCreate = isPendingCreate;
                IsEmpty = isEmpty;
            }

            public static FolderEntry Existing(string name, string relativePath, bool isEmpty) =>
                new(name, relativePath, null, false, isEmpty);

            public static FolderEntry Pending(string parentRelativePath) =>
                new("New Folder", null, parentRelativePath, true, false);
        }

        private readonly struct RowState
        {
            public readonly FolderEntry Entry;
            public readonly int Id;
            public readonly IVisualElementScheduledItem ScheduledItem;

            public RowState(FolderEntry entry, int id, IVisualElementScheduledItem scheduledItem)
            {
                Entry = entry;
                Id = id;
                ScheduledItem = scheduledItem;
            }
        }
    }


}